on:
  pull_request:
    branches:
      - staging
  push:
    branches:
      - staging
      - master

jobs:
#  lint:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-go@v2
#        with:
#          stable: 'false'
#          go-version: '1.17.3'
#
#      - name: Download & Run Linter
#        run: |
#          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.26.0
#          golangci-lint run
  test:
    ## We want to define a strategy for our job
    strategy:
      ## this will contain a matrix of all of the combinations
      ## we wish to test again:
      matrix:
        go-version: [ 1.17.x ]
        platform: [ ubuntu-latest]

    ## Defines the platform for each test run
    runs-on: ${{ matrix.platform }}

    ## the steps that will be run through for each version and platform
    ## combination
    steps:
      ## sets up go based on the version
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Test
#        run: go test ./...
        run: |
          CVPKG=$(go list ./... | grep -v mocks | tr '\n' ',')
          go test -vet off -coverpkg=${CVPKG} -coverprofile=coverage.out -covermode=count  ./...
